map2: map2.o list2.o 
	gcc -g -o map2 map2.o  list2.o -lm

list2.o: list2.c list2.h 
	gcc -g -c -Wall list2.c 
tree2.o: tree2.c tree2.h 
	gcc -g -c -Wall tree2.c 
map2.o: map2.c 
	gcc -g -c -Wall map2.c


